apiVersion: v1
kind: Service
metadata:
  name: deployment-dashboard
  namespace: platform-staging
spec:
  selector:
    app: deployment-dashboard
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

